### ISSUE TITLE
Recreate existing GOVUK Elements

### ISSUE THREAD

**Issue by paulmsmith** [dwpdigitaltech/dwp-design#32]
Before Christmas, I discussed with @gemmaleigh the value of us 'componentising' the existing GOVUK Elements within our Fractal.

As GDS are busy concentrating on the build of the new GOVUK Frontend architecture us doing this work might help form a legacy documentation for the many sites and services that will still be using the current front-end tools and assets.

I notice that @htmlandbacon has created [GOVUK Elements Nunjucks](https://github.com/htmlandbacon/govuk-elements-nunjucks) I wonder if what he is doing might be done in our Fractal? Or if it is something different? Let me know Colin. :)

**Comment by htmlandbacon** [comment]
The repo is to tidy up work I shared back in February around [nunjucks helpers](https://github.com/htmlandbacon/nunjucks-helpers). There didn't seem much interested in re-using them so I only really did [docs](https://nunjucks-macros-example.herokuapp.com/) (olds style) as a test.

I'm now at the point where I have multiple services, so it seemed wise to follow @gunjam and make a tested, component based version that didn't live with my code, following similar to [govuk-elements-marko](https://github.com/gunjam/govuk-elements-marko).

I'm not quite sure how far Factal goes for building out these things, but I can see it getting bloated if it has marko, nunjucks, freemarker and angularjs examples.

**Comment by paulmsmith** [comment]
I was going to just include nunjucks examples in our Fractal as thought maybe what you were doing could be included but suspect it's slightly different. I'd love to see what it is you do in this repo so I'll watch it. Thanks for the reply @htmlandbacon

**Comment by paulmsmith** [comment]
Having a look at @htmlandbacon's current effort, it is very similar to what I was going to do for the design system components.

I think it's probably worth waiting for Colin to finish and and just use Fractal to document it? You could drop it in if you wanted @htmlandbacon? or I can do it with your help? No point doing the same work twice, also, like @gunjam's work the NPM package will useful. No reason we couldn't include both in the Fractal examples.

This [template gov-input template file](https://github.com/htmlandbacon/govuk-elements-nunjucks/blob/master/components/gov-input/template.njk) could easily be dropped into Fractal with a config file for the data.

cc: @jonhurrell

**Comment by htmlandbacon** [comment]
I'll be pushing it to NPM after I've worked out how to not make them variable heavy but configurable for my current front-end projects.

I fear it will just become dead code otherwise.

I'll take a look at how to pull it into Fractal and display it after I've finished cleaning up the first component.

**Comment by paulmsmith** [comment]
@htmlandbacon Excellent! Thanks. :)

@tsmorgan Is having a try at porting GOVUK elements to get familiar with Fractal. I'm going to be doing the same but it would be ace to have that decoupled dependancy like you're doing which can automatically utilised and then documented in Fractal.
