### ISSUE TITLE
Add CSS stats

### ISSUE THREAD

**Issue by paulmsmith** [dwpdigitaltech/dwp-design#5]
Trial CSS stats as a tool for monitoring the quality of the CSS codebase.

**Comment by jonhurrell** [comment]
Maybe worth integrating a [specificity-graph](https://github.com/pocketjoso/specificity-graph).

**Comment by paulmsmith** [comment]
Yes absolutely. Good that we're going to see GDS because all this is dependant on their work. We're at the mercy of the code they give us to work with. They're using ITCSS so hoping they are on the right track and we'll see only high spikes where they should be. (trumps whatever @csswizardry calls them now). ;)

**Comment by csswizardry** [comment]
Officially called _Utilities_, because of hopefully obvious reasons :(

**Comment by paulmsmith** [comment]
Thanks @csswizardry. You going to be working with NHS Digital again? If you're in Leeds regular I'd love to organise a show-and-tell between NHS and DWP when you've got something to show.

**Comment by csswizardry** [comment]
That’s a pretty nice idea! Pinging @cehwitham, @jdbrew.
